### ISSUE TITLE
Remove un-needed code

### ISSUE THREAD

**Issue by SwipeX** [CISC-475-Team-2/Front-End-MVC#3]
This project was set up with quite a bit of un-needed code that we will not require.

**Comment by mgriner** [comment]
I removed some of this.

**Comment by SwipeX** [comment]
Looks fine, there isnt much need to strip it down any more. I will close this, just in an ideal situation, it seems as though we would only want exactly the bare minimum amount of code -- without bloat (However this will be fine in our case).
