### ISSUE TITLE
Merge MVC to Front end

### ISSUE THREAD

**Issue by SwipeX** [CISC-475-Team-2/Front-End-MVC#4]
This needs to be done in a way to preserve the issues and scrum.  I will try to handle this today.

**Comment by mgriner** [comment]
Any luck?  We could probably pull the Front-End repo, delete everything locally and push.  Then pull down from this repo into local Front-End and push back to remote Front-End.  That way history and scrum is preserved.  There might be an easier way, never done it.

**Comment by SwipeX** [comment]
I'm guessing that is the most applicable way for us to do this.  There probably is some way with branching and git that we *should* have used, but my git knowledge is rather limited, so what you expressed will probably work fine.

**Comment by SwipeX** [comment]
To add: I tried to do that exact thing and was getting commit issues.

**Comment by mgriner** [comment]
Okay, I will try and take a look at it later tonight.

**Comment by mgriner** [comment]
@SwipeX Good to go, the Front-End Repo is now the MVC project.

**Comment by SwipeX** [comment]
Great. I'm glad that it worked as we thought.
